### ISSUE TITLE
ølflaske adaptor - teknologiundersøgelse

### ISSUE THREAD

**Issue by ExhaustedPanda** [TrulyTame/Smart-Beerbong#40]

**Comment by Hestehviskeren** [comment]
Tjekke materiale udvidelse af 3d print fleksibel materiale fra 3D Lab, og se om den flaske-læbe kan passe til både Carlsberg og Unibrew efter funktionelle krav (fortrinsvis en adapter der passer begge halse - afhængigt af kompressibiliteten af print materiale og indre struktur)
- Designe prototype ud fra mål af flaskehalse (Carlsberg + Unibrew - 33cl)
